---
- name: Create backup directory if not exists
  file:
    path: "{{backup_dir}}"
    state: directory
    mode: '0755'

- name: show run on device
  ios_command:
    commands:
      - show run
  register: config

- name: save output to ansible host
  copy:
    content: "{{config.stdout[0]}}"
    dest: "{{backup_dir}}/config-{{ inventory_hostname }}-{{ansible_date_time}}.conf"

