---
- name: show run on device
  ios_command:
    commands:
      - show run
  register: config

- name: save output to ansible host
  copy:
    content: "{{config.stdout[0]}}"
    dest: "~/cisco-backup/backups/{{hostvars.localhost.DTG}}"

